### PR TITLE
Molecule2

### LINKED ISSUE #3: Proposal for standard molecule scenarios
Following https://github.com/openmicroscopy/ome-ansible-molecule-dependencies/pull/10 molecule will support multiple scenarios.

At present this repo has to handle roles which can't be tested in Travis, for example because they require low-level OS configuration or they require additional resources: https://github.com/ome/ansible-roles/blob/749e53100885a52841d821c7048f38692212537f/.travis.yml#L19-L24

Suggestions:
- All roles must have a `default` scenario which can be run by developers. This would preferably use Docker, but if that's insufficient for testing then Vagrant
- If the `default` scenario uses Docker then optionally provide a `vagrant` scenario
- If the `default` scenario does not work in Travis there must be a scenario named `travis`. For example this may only run a syntax check in molecule.
- Remove the fallback handling in the test script https://github.com/ome/ansible-roles/blob/749e53100885a52841d821c7048f38692212537f/scripts/test.sh#L7-L11

### PR DESCRIPTION
**Pull request by sbesson**
Fixes #3 

This is a proposed implementation of the changes described in #3. In particular `scripts/test.sh` is updated to check for a scenario name `travis` (independent of the directory name) and falls back to testing the `default` scenario. The submodules are updated so at the moment, only two roles (basedeps and ssl-certificate) should pass with the new setup.

### CODE REVIEW

**Comment by manics** [comment]
Good timing...I've just broken the proposal 🤣 https://github.com/openmicroscopy/ansible-role-java/pull/6

**Comment by sbesson** [comment]
Looking at the content of the above, if we start moving towards a flexible number of scenarios per role rather than using name-based conventions, one possibleto update #3 would be to update the logic in https://github.com/ome/ansible-roles/blob/master/scripts/update.py to:

1- detects all role repos
2- exclude known deprecated roles and Molecule 2 incompatible roles (via the presence of a `molecule` folder?)
4- parse `.travis.yml` file for all tested `SCENARIO` values (defaulting to `default` if none)
5- constructs the `env` matrix with pairs of `(ROLE, SCENARIO)`
6- run `molecule test -s SCENARIO`

**Comment by sbesson** [comment]
Last commit is probably failing due to the [Molecule 2.20](https://molecule.readthedocs.io/en/2.20/changelog.html) release -see also discussion in https://github.com/IDR/deployment/pull/173#issuecomment-478480505.

**Comment by manics** [comment]
This means we'll no longer be testing roles that haven't been upgraded. Notably this includes omero-server and omero-web.

**Comment by sbesson** [comment]
Yes, that's the trade-off. Note however the `omero-server` role has been consistently failing the cron job for [the past month](https://travis-ci.org/ome/ansible-roles/builds) (separate issue which I will fix shortly).
Would you set  the migration of `omero-server` and `omero-web` incl. dependency roles as the threshold for switching to Molecule 2+ only testing ?

**Comment by manics** [comment]
They're our main public-facing ones so that seems like a good requirement. Alternatively we could setup cron jobs on the omero-web and omero-server repos, and merge this PR now?

**Comment by sbesson** [comment]
That's fine, I second the statement to target the migration of `openmicroscopy.omero-{server,web}` before updating this repository. 

> Alternatively we could setup cron jobs on the omero-web and omero-server repos, and merge this PR now?

The goal of this repository was primarily to reduce the need to set up and maintain per-repo Travis cron jobs. I am completely fine with closing this PR for now and resurrecting it once the above is achieved. Giving @joshmoore a chance to comment before I do to.

**Comment by joshmoore** [comment]
My initial thoughts were similar: "oh dear, what about all the removed repos". So :+1: for defining a minimal critical set and getting those added here.

**Pull request closed without merging**
